export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCC = 'GET_ALL_USERS_SUCC';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCC = 'ADD_USER_SUCC';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_ALL_PRODUCT_SUCC = 'GET_ALL_PRODUCT_SUCC';
export const GET_ALL_PRODUCT_FAIL = 'GET_ALL_PRODUCT_FAIL';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCC = 'ADD_PRODUCT_SUCC';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCC = 'EDIT_PRODUCT_SUCC';
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCC = 'DELETE_PRODUCT_SUCC';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CATEGORY_SUCC = 'GET_ALL_CATEGORY_SUCC';
export const GET_ALL_CATEGORY_FAIL = 'GET_ALL_CATEGORY_FAIL';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCC = 'DELETE_CATEGORY_SUCC';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_SUCC = 'EDIT_CATEGORY_SUCC';
export const EDIT_CATEGORY_FAIL = 'EDIT_CATEGORY_FAIL';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCC = 'ADD_CATEGORY_SUCC';

export const GET_ALL_CLIENT = 'GET_ALL_CLIENT';
export const GET_ALL_CLIENT_SUCC = 'GET_ALL_CLIENT_SUCC';
export const GET_ALL_CLIENT_FAIL = 'GET_ALL_CLIENT_FAIL';

export const ADD_CLIENT = 'GET_ALL_CLIENT';
export const ADD_CLIENT_SUCC = 'GET_ALL_CLIENT_SUCC';
export const ADD_CLIENT_FAIL = 'GET_ALL_CLIENT_FAIL';






