export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCC = 'GET_ALL_USERS_SUCC';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCC = 'ADD_USER_SUCC';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCC = 'EDIT_USER_SUCC';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCC = 'DELETE_USER_SUCC';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_ALL_PRODUCT_SUCC = 'GET_ALL_PRODUCT_SUCC';
export const GET_ALL_PRODUCT_FAIL = 'GET_ALL_PRODUCT_FAIL';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCC = 'ADD_PRODUCT_SUCC';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCC = 'EDIT_PRODUCT_SUCC';
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCC = 'DELETE_PRODUCT_SUCC';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CATEGORY_SUCC = 'GET_ALL_CATEGORY_SUCC';
export const GET_ALL_CATEGORY_FAIL = 'GET_ALL_CATEGORY_FAIL';

export const GET_ALL_CATEGORY_BI = 'GET_ALL_CATEGORY_BI';
export const GET_ALL_CATEGORY_SUCC_BI = 'GET_ALL_CATEGORY_SUCC_BI';
export const GET_ALL_CATEGORY_FAIL_BI = 'GET_ALL_CATEGORY_FAIL_BI';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCC = 'DELETE_CATEGORY_SUCC';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_SUCC = 'EDIT_CATEGORY_SUCC';
export const EDIT_CATEGORY_FAIL = 'EDIT_CATEGORY_FAIL';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCC = 'ADD_CATEGORY_SUCC';
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL';

//CLIENT
export const GET_ALL_CLIENT = 'GET_ALL_CLIENT';
export const GET_ALL_CLIENT_SUCC = 'GET_ALL_CLIENT_SUCC';
export const GET_ALL_CLIENT_FAIL = 'GET_ALL_CLIENT_FAIL';

export const ADD_CLIENT = 'ADD_CLIENT';
export const ADD_CLIENT_SUCC = 'ADD_CLIENT_SUCC';
export const ADD_CLIENT_FAIL = 'ADD_CLIENT_FAIL';

export const EDIT_CLIENT = 'EDIT_CLIENT';
export const EDIT_CLIENT_SUCC = 'EDIT_CLIENT_SUCC';
export const EDIT_CLIENT_FAIL = 'EDIT_CLIENT_FAIL';

export const DELETE_CLIENT = 'DELETE_CLIENT';
export const DELETE_CLIENT_SUCC = 'DELETE_CLIENT_SUCC';
export const DELETE_CLIENT_FAIL = 'DELETE_CLIENT_FAIL';

//Company

export const GET_ALL_COMPANY = 'GET_ALL_COMPANY';
export const GET_ALL_COMPANY_SUCC = 'GET_ALL_COMPANY_SUCC';
export const GET_ALL_COMPANY_FAIL = 'GET_ALL_COMPANY_FAIL';

export const EDIT_COMPANY = 'EDIT_COMPANY';
export const EDIT_COMPANY_SUCC = 'EDIT_COMPANY_SUCC';
export const EDIT_COMPANY_FAIL = 'EDIT_COMPANY_FAIL';

//Devis

export const GET_ALL_DEVIS = 'GET_ALL_DEVIS';
export const GET_ALL_DEVIS_SUCC = 'GET_ALL_DEVIS_SUCC';
export const GET_ALL_DEVIS_FAIL = 'GET_ALL_DEVIS_FAIL';

export const ADD_DEVIS = 'ADD_DEVIS';
export const ADD_DEVIS_SUCC = 'ADD_DEVIS_SUCC';
export const ADD_DEVIS_FAIL = 'ADD_DEVIS_FAIL';

export const EDIT_DEVIS = 'EDIT_DEVIS';
export const EDIT_DEVIS_SUCC = 'EDIT_DEVIS_SUCC';
export const EDIT_DEVIS_FAIL = 'EDIT_DEVIS_FAIL';

export const DELETE_DEVIS = 'DELETE_DEVIS';
export const DELETE_DEVIS_SUCC = 'DELETE_DEVIS_SUCC';
export const DELETE_DEVIS_FAIL = 'DELETE_DEVIS_FAIL';

export const GET_PROD_BY_NAME = 'GET_PROD_BY_NAME';
export const GET_PROD_BY_NAME_SUCC = 'GET_PROD_BY_NAME_SUCC';
export const GET_PROD_BY_NAME_FAIL = 'GET_PROD_BY_NAME_FAIL';

//temp devis



export const ADD_TEMP_DEVIS = 'ADD_TEMP_DEVIS';
export const ADD_TEMP_DEVIS_SUCC = 'ADD_TEMP_DEVIS_SUCC';
export const ADD_TEMP_DEVIS_FAIL = 'ADD_TEMP_DEVIS_FAIL';





